sudo: false
language: node_js
node_js: 10
script:
  - npm run test:prod
  - npm run lint
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run build:docs
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  github-token: $GH_TOKEN
  on:
    branch: master
notifications:
  email: false
